fieldLayouts:
  b802e201-2919-4136-a2d5-369bcfeba516:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: local
hasUrls: true
name: Local
settings:
  path: /var/www/html/web/images
sortOrder: 1
type: craft\volumes\Local
url: '@web/images'
